dist: trusty
language: python
python:
  - "3.7-dev"
install: |
  set -e
  set -o pipefail
  #pip install -e .
  pip list
script: |
  set -e
  set -o pipefail
  #ci/run-tests.sh
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-rc\d+)?$/
